### ISSUE TITLE
Convert to MIT

### ISSUE THREAD

**Issue by LeoDog896** [emortalmc/LazerTag#24]
I agree with converting my current commits: 
- https://github.com/emortalmc/LazerTag/commit/f457641d387c84369f37a73983044fb967117e49
- https://github.com/emortalmc/LazerTag/commit/788670b6568a0354c7f268713d651609159b0f92
- https://github.com/emortalmc/LazerTag/commit/f81ecd41c5d5dd5c380c440b058c1e27b4869470

@LooFifteen, @emortaldev  do you agree with moving your code changes to MIT?

**Comment by LooFifteen** [comment]
I agree to change to MIT, the superior license.

**Comment by emortaldev** [comment]
woo
